server:
  port: 9999
  host: larek.tech
  cors:
    - http://localhost:9999
    - http://localhost:5173
    - https://larek.tech

pg:
  dsn: postgresql://pg-user:pg-password@pg:5432/t1-dev

auth:
  jwt_secret: hello_world