volumes:
  pg_admin:

services:
  backend:
    image: ghcr.io/egortarasov/example/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    volumes:
      - ./docker-config.yaml:/root/config.yaml
    ports:
      - "9999:9999"
    command: ./main
    restart: always
  migrations:
    build:
      context: ./backend
      dockerfile: Dockerfile.migration
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-pg-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pg-password}
      - POSTGRES_DB=${POSTGRES_DB:-t1-dev}
      - POSTGRES_HOST=${POSTGRES_HOST:-pg}
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-pg-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pg-password}
      - POSTGRES_DB=${POSTGRES_DB:-t1-dev}
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pg-user} -d ${POSTGRES_DB:-t1-dev}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-tarasov.egor.yandex@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-cisco}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pg_admin:/var/lib/pgadmin
    ports:
      - "10000:80"
  # clickhouse:
  #   image: clickhouse/clickhouse-server:23.3-alpine

  #   hostname: clickhouse
  #   volumes:
  #   - ${PWD}/fs/volumes/clickhouse/users.d/users.xml:/etc/clickhouse-server/users.xml"
  #   ports:
  #   - "8123:8123"
  #   - "9990:9000"
  #   - "9009:9009"
  #   ulimits:
  #     nproc: 65535
  #     nofile:
  #       soft: 262144
  #       hard: 262144

  grafana:
    build:
      context: ${PWD}/docker/
      dockerfile: grafana.Dockerfile
    hostname: grafana

    environment:
    - GF_SECURITY_ALLOW_EMBEDDING=${GF_SECURITY_ALLOW_EMBEDDING:-true}
    - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-password}
    - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED:-true}
    - GF_AUTH_ANONYMOUS_ORG_ROLE=${GF_AUTH_ANONYMOUS_ORG_ROLE:-Admin}
    - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    volumes:
      - ${PWD}/fs/volumes/grafana/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"