// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPipeLine = `-- name: CreatePipeLine :one
INSERT INTO pipelines(user_id, title, pipeline_description)
VALUES ($1, $2, $3)
RETURNING id,
    user_id,
    title,
    created_at,
    updated_at
`

type CreatePipeLineParams struct {
	UserID              int64
	Title               string
	PipelineDescription string
}

type CreatePipeLineRow struct {
	ID        int64
	UserID    int64
	Title     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) CreatePipeLine(ctx context.Context, arg CreatePipeLineParams) (CreatePipeLineRow, error) {
	row := q.db.QueryRow(ctx, createPipeLine, arg.UserID, arg.Title, arg.PipelineDescription)
	var i CreatePipeLineRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
