// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DataBlock struct {
	ID             int32
	InputBlockID   pgtype.Int8
	StorageUrl     string
	StorageType    string
	TextSplitterID int64
	VectorStoreID  int64
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type InputBlock struct {
	ID          int32
	PipelineID  pgtype.Int8
	DataBlockID int64
	LlmID       int64
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
}

type LlmBlock struct {
	ID            int32
	InputBlockID  pgtype.Int8
	LlmEndpoint   string
	LlmType       string
	Model         string
	Prompt        string
	Template      string
	WidgetBlockID int64
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type OauthProvider struct {
	ID   int32
	Name string
}

type OauthUser struct {
	ID             int32
	UserID         pgtype.Int4
	ProviderID     pgtype.Int4
	ProviderUserID string
}

type Pipeline struct {
	ID                  int32
	UserID              pgtype.Int8
	Title               string
	PipelineDescription string
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
	DeletedAt           pgtype.Timestamp
}

type Role struct {
	ID   int32
	Name string
}

type TelegramDatum struct {
	TelegramID   int64
	UserID       pgtype.Int8
	Username     pgtype.Text
	FirstName    pgtype.Text
	LastName     pgtype.Text
	LanguageCode pgtype.Text
	LastActivity pgtype.Timestamp
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
}

type TextSplitter struct {
	ID           int32
	DataBlockID  pgtype.Int8
	SplitterType string
	Config       string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type User struct {
	ID           int32
	Email        string
	PasswordHash pgtype.Text
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type UserRole struct {
	UserID int32
	RoleID int32
}

type VectorStore struct {
	ID               int32
	DataBlockID      pgtype.Int8
	StoreType        string
	CollectionName   string
	PersistDirectory string
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type WidgetBlock struct {
	ID         int32
	LlmBlockID pgtype.Int8
	ImageUrl   string
	Styles     []byte
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}
