// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OauthProvider struct {
	ID   int32
	Name string
}

type OauthUser struct {
	ID             int32
	UserID         pgtype.Int4
	ProviderID     pgtype.Int4
	ProviderUserID string
}

type Role struct {
	ID   int32
	Name string
}

type TelegramDatum struct {
	TelegramID   int64
	UserID       pgtype.Int8
	Username     pgtype.Text
	FirstName    pgtype.Text
	LastName     pgtype.Text
	LanguageCode pgtype.Text
	LastActivity pgtype.Timestamp
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	DeletedAt    pgtype.Timestamp
}

type User struct {
	ID           int32
	Email        string
	PasswordHash pgtype.Text
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type UserRole struct {
	UserID int32
	RoleID int32
}
